### ISSUE TITLE
Imrovement: Allow md4 to consume prepared byte array

### ISSUE THREAD

**Issue by pavelhoral** [emn178/js-md4#1]
I love the simplicity of this library. We have use cases where we want also compute hash of non UTF-8 based source. It would be very helpful if the library can accept already prepared byte array in one of the following form: Uint8Array, Int8Array or Array with integer numbers (0-255).

**Comment by emn178** [comment]
I added this feature in v0.2.0 and thanks for suggestion.

**Comment by pavelhoral** [comment]
I've verified that your implementation covers the initial use-case (computing NT hash). 

Thank you, closing as resolved.

**Comment by pavelhoral** [comment]
Just a quick question - will you publish 0.2.0 to NPM? Right now it says the newest release is 0.1.1. Thank you. https://www.npmjs.com/package/js-md4

**Comment by emn178** [comment]
sorry, forgot to publish.
